function Hd = bandpass_filter1
%BANDPASS_FILTER1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 29-Sep-2018 14:59:38

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 128;  % Sampling Frequency

Fstop1 = 7.5;             % First Stopband Frequency
Fpass1 = 10;               % First Passband Frequency
Fpass2 = 12;              % Second Passband Frequency
Fstop2 = 13.5;            % Second Stopband Frequency
Dstop1 = 1e-05;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 1e-05;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
